### ISSUE TITLE
Πεδιο για ποσοστά και χρήματα 

### ISSUE THREAD

**Issue by apanagio** [mou-gr/forms#10]
Χρήση των πεδιων currency και percentage του Alpaca όπου χρειάζεται.
Όπως στο 3.Δ.2.1

**Comment by apanagio** [comment]
Δεν υπάρχει για percentage. 
Θα πρέπει να χρησιμοποιήσουμε το currency αλλά αντί για "€" να βάλουμε "%"

**Comment by grtheod** [comment]
Για το %, δεν υπάρχει τρόπος να ελέγξουμε αν το νούμερο που μας δίνεται με το currency είναι μικρότερο από κάποιο max, παρά μόνο το πλήθος των ψηφίων(το πεδίο είναι string). Επομένως, ή να μπει ως : 
               "type": "currency",
              "centsSeparator": ",",
               "prefix": "",
               "suffix": "%"
στα options του alpaca και να γίνει έλεγχος με js ή να γίνει μόνο έλεγχος με js και να μπένει το % με το χέρι.

Επίσης τα 3.Ε.1 και 3.Ε.3 πρέπει να έχουν currency; Γιατί βλέπω στο 3.json ότι υπάρχει το 
                            "items": {
				"$ref": "#/definitions/companySize"
			     }

**Comment by apanagio** [comment]
το $ref είναι στο αρχείο schema.json πανω πανω στο τμήμα definitions.
Τα άλλα πεδία μπορούμε να τα κάνουμε strings δεν πειράζει

**Comment by apanagio** [comment]
Δεν θα υλοποιηθεί προς το παρόν
