### ISSUE TITLE
Αλλαγή των labels

### ISSUE THREAD

**Issue by apanagio** [mou-gr/forms#11]
Πρέπει στη φόρμα κάθε πεδίο να φαίνεται με μοναδικό άριθμο πχ 5.2.1.0 όπως είναι και στο doc της αίτησης. Ακομα και οι πίνακες που στο έγγραφο δεν έχουν μοναδικό αριθμό θα πρέπει να αποκτήσουν.

**Comment by grtheod** [comment]
Να βάλω μοναδικό αριθμό και στις γραμμές των πινάκων; Π.χ. 5.1.α1 κτλ;
