### ISSUE TITLE
Αυτόματα πεδία 

### ISSUE THREAD

**Issue by apanagio** [mou-gr/forms#13]
Όλα τα πεδία που υπολογιζονται αυτοματα όπως τα άθροισμα τα και τα ποσοστά να υπολογιζονται και να γίνουν και readonly.

**Comment by apanagio** [comment]
Με τις τελευταίες αλλαγές,
αρκεί να μπει η class auto-sum στον πίνακα και οι κλάσσεις sum-col και per-col στις στήλες με το άθροισμα και τα ποσοστά αντίστοιχα.
πχ array28

**Comment by ncppd** [comment]
ready
