### ISSUE TITLE
Όταν διαγράφεται μια γραμμή δεν ανανεώνεται το άθροισμα

### ISSUE THREAD

**Issue by ncppd** [mou-gr/forms#15]
Στους δυναμικούς πίνακες θα έπρεπε κατά την διαγραφή μίας γραμμής να τρέξει η συνάρτηση αθροίσματος.

**Comment by grtheod** [comment]
Βρήκα τρόπο να πιάνει τα actions όταν πατηθεί το remove button, αλλά πρέπει να βελτιωθεί η λογική των sum και perc, ώστε να μην επαναλάβουμε ξανά τον ίδιο κώδικα σε αυτό το σημείο.
