### ISSUE TITLE
προσθηκη gant chart στο τμημα 8

### ISSUE THREAD

**Issue by apanagio** [mou-gr/forms#16]
Στο τμήμα 8 θα ήταν ωραίο να δημιουργείται αυτόματα ένα gant διαγραμμα με τα καταχωρημένα στοιχεία

**Comment by grtheod** [comment]
Νομίζω δεν υπάρχει τρόπος να κάνει hide συγκεκριμένα bar (show:false), οπότε έκανα τα πρώτα data να έχουν άσπρο χρώμα. Για να φαίνεται ωραίο πρέπει να αφαιρεθούν οι κάθετες/οριζόντιες γραμμές. Δεν έχω φτιάξει το διάβασμα γτ θα αρχίσω να κοιτάω τον κώδικα που μου δώσατε.

**Comment by apanagio** [comment]
done
