### ISSUE TITLE
Κατά την πρόσθεση νέου δυναμικού πίνακα δεν τρέχει η συνάρτηση της κλασης auto-sum

### ISSUE THREAD

**Issue by ncppd** [mou-gr/forms#18]
Παρόλα αυτά η κλάση περνιέται στον νέο πίνακα.

**Comment by apanagio** [comment]
http://stackoverflow.com/questions/203198/event-binding-on-dynamically-created-elements

Δεν υπάρχει ο πίνακας όταν γίνεται bind το event οπότε πρέπει να γίνει δυναμικά όπως λέει το link πανω
