### ISSUE TITLE
Test ΑΜΘ

### ISSUE THREAD

**Issue by ikessanlis** [mou-gr/forms#2]
Δοκιμαστικό TEST από την ΕΥΔ ΕΠ ΑΜΘ.

Ευχαριστώ,

ΓΙάννης Κεσανλής

**Comment by apanagio** [comment]
Στο http://195.167.92.105:8000/AM8/ θα βρείτε την φόρμα υποβολής για τη δράση της ΑΜΘ. 
Παρακαλώ υποβάλλετε της παρατηρήσεις σας δημιουργώντας ένα καινούριο issue για να ενσωματωθούν. Επισημαίνω ότι μέχρι στιγμής έτοιμα είναι τα 3 πρώτα βήματα. Πιστέυω ότι μέχρι και αύριο θα είναι έτοιμη ολόκληρη η φόρμα.

**Comment by ikessanlis** [comment]
Τα 3 πρώτα βήματα φαίνονται εντάξει, σύμφωνα με την πλέον επικαιροποιημένη έκδοση του εντύπου «Παράρτημα 5, Υπόδειγμα Εντύπου Υποβολής Αίτησης - ΠΣΚΕ ΕΥΚΕ», που είχαμε αποστείλει στην ΤΕΠΨΤ.

Παρακαλούμε ενημερώστε μας για την εξέλιξη της προσπάθειάς σας, ούτως ώστε να την ελέγξουμε το συντομότερο δυνατό.

Ευχαριστούμε προκαταβολικά και παραμένουμε στη διάθεσή σας για πληροφορίες ή/και παρατηρήσεις.

Με εκτίμηση,

Ιωάννης Κεσανλής
Μονάδα A', Προγραμματισμού & Αξιολόγησης
Ειδική Υπηρεσία Διαχείρισης Επιχειρησιακού Προγράμματος
Περιφέρειας Ανατολικής Μακεδονίας και Θράκης
Δ/νση:  Ηροδότου 28, 69132 Κομοτηνή
Τηλ:     2531352332
Fax:     2531081601
E-mail: ikessanlis@mou.gr<mailto:ikessanlis@mou.gr>
Web:    www.eydamth.gr<http://www.eydamth.gr/>

**Comment by apanagio** [comment]
Και το 4ο βήμα είναι έτοιμο, παρακαλώ δείτε το και σχολιάστε το.

**Comment by ikessanlis** [comment]
Καλημέρα σας,

Κατ’ αρχάς, σας ευχαριστούμε πολύ για την άμεση ανταπόκριση!


1.    Στη φόρμα που παραμετροποιήσατε τώρα, στο 3ο Βήμα, παρατηρούμε ότι απουσιάζει εντελώς το τμήμα 3.ΣΤ, του Παραρτήματος 5 (Υπόδειγμα Εντύπου Υποβολής Αίτησης - ΠΣΚΕ ΕΥΚΕ), όπως κατωτέρω:

3.ΣΤ


Περιγράφονται με τρόπο απόλυτα κατανοητό τα παρακάτω πεδία που αφορούν στην επιχείρηση:

  1.  Σύντομο ιστορικό, έτος έναρξης δραστηριότητας της επιχείρησης,
  2.  Περιγραφή Στρατηγικής της επιχείρησης,
  3.  Ανάλυση επιχειρηματικής δραστηριότητας,
  4.  Διαδικασίες οργάνωσης - προσωπικό,
  5.  Συνοπτική παρουσίαση της παραγωγικής διαδικασίας.



Επιπλέον, εφόσον υπάρχουν, μνημονεύονται:

  1.  Παραγωγικά μέσα για έρευνα (προσωπικό, εξοπλισμός, κονδύλια) - Επίπεδα Τεχνολογικής Ετοιμότητας,
  2.  Συμμετοχές σε Ευρωπαϊκούς ή Διεθνείς διαγωνισμούς που διοργανώθηκαν από κοινοτικό, εθνικό, διεθνή ή εμπορικό φορέα και έχει βραβευτεί ή διακριθεί σε κάποια κατηγορία,
  3.  Εμπορικά Σήματα,
  4.  Συστήματα διασφάλισης ποιότητας παραγωγικής διαδικασίας,
  5.  Συστήματα αυτομ/σης για την παρακολούθηση και τον έλεγχο της "παραγωγικής" διαδικασίας,
  6.  Εξειδικευμένα Λογισμικά (ERP, CRM, Logistics, κ.α.),
  7.  Ηλεκτρονικές πωλήσεις,
  8.  Αυτόματα συστήματα παραγγελιοληψίας (remote, κ.α.),
  9.  Οργανωμένη προβολή (επαγγελματικοί οδηγοί, μηχανές αναζήτησης),
  10. Λειτουργία e-shop,
  11. Εταιρική ιστοσελίδα,
  12. Συμφωνητικά ή και Προσύμφωνα πώλησης νέων προϊόντων/ υπηρεσιών,


Μήπως σκοπεύετε να το εντάξετε σε κάποια άλλη ενότητα του εντύπου;


2.    Προχωρώντας στο 4ο Βήμα, στις ενότητες 4α έως και 4γ, καλό θα ήταν, εφόσον είναι εφικτό, να προσθέταμε (με μικρότερη γραμματοσειρά & δίχως «έντονη γραφή»-bold- ίσως…?) και τις σύντομες «οδηγίες» που περιλαμβάνονται στο έντυπο που σας αποστείλλαμε (με πλάγια γράμματα στο υπόδειγμα – “italics”)

4. ΑΝΑΛΥΤΙΚΑ ΣΤΟΙΧΕΙΑ ΤΟΥ ΕΡΓΟΥ ΩΣ ΠΡΟΣ ΤΟ ΦΥΣΙΚΟ ΑΝΤΙΚΕΙΜΕΝΟ  & ΤΙΣ ΕΠΙΠΤΩΣΕΙΣ

4α Περιγραφή  Επενδυτικού Σχεδίου  (έως 1000 χαρακτήρες)
Περιγράφεται το στάδιο ανάπτυξης και προστιθέμενης αξίας του επενδυτικού σχεδίου, καθώς και η κατανόηση ανταγωνιστικών λύσεων. Δύναται να περιληφθεί και σύγκριση με «ιδεατές», γνωστές εμπορικές λύσεις


Όριο στα mb (πχ 5 για κάθε εντυπο) μέχρι 25 στο σύνολο της πράξης


4β Αντικείμενο του Επενδυτικού Σχεδίου – Αναμενόμενα Αποτελέσματα
Περιγράφονται:
• Η στόχευση νέων ευκαιριών της αγοράς,
• Η δυνατότητα ενίσχυσης της ανάπτυξης της εταιρίας,
• Η πειστικότητα επιδόσεων πρότασης και «value for money»,
• Η κατανόηση κινδύνων κι ευκαιριών για την επιτυχή εισαγωγή της καινοτομίας στην αγορά, από τεχνικής κι από εμπορικής απόψεως,
• Η ύπαρξη ζήτησης/αγοράς για την καινοτομία,
• Περιγραφή Παραδοτέων.


4γ Ωριμότητα Επενδυτικού Σχεδίου
Περιγράφονται:
• Οι άδειες που απαιτούνται για την έναρξη της υλοποίησης του επιχειρηματικού σχεδίου,
• Η ρεαλιστικότητα του χρονοδιαγράμματος,
• Η ρεαλιστικότητα του προϋπολογισμού,
• Η καταλληλότητα του οργανωτικού σχήματος, εάν δηλαδή η πρόταση αποδεικνύει ότι το έργο έχει τους σχετικούς πόρους (προσωπικούς, εγκαταστάσεις, δίκτυα, κλπ.) για την ανάπτυξη των δραστηριοτήτων του και τους ρόλους που θα διαδραματίσουν οι μετέχοντες,
• Η επάρκεια του δυναμικού της επιχείρησης για την υλοποίηση της πρότασης.


Για την πληρέστερη αξιολόγηση της πρότασης, δύναται να επισυναφθεί στην αίτηση ηλεκτρονικά, αρχείο (έως 10 σελίδες Α4), που θα περιλαμβάνει πρόσθετες επεξηγηματικές πληροφορίες των ανωτέρω.


3.    Περαιτέρω, προς αποφυγή παρανοήσεων, και διευκόλυνση της διαδικασίας αξιολόγησης, μάλλον θα πρέπει να μετονομάσουμε την ενότητα
«4.1 Κ.Α.Δ. ΕΠΕΝΔΥΤΙΚΟΥ ΣΧΕΔΙΟΥ (NACE Level Group)», σε
«4.1α Κ.Α.Δ. ΕΠΕΝΔΥΤΙΚΟΥ ΣΧΕΔΙΟΥ (NACE Level Group)»,
και την ενότητα
«4.1 ΠΙΝΑΚΑΣ ΕΝΟΤΗΤΩΝ ΕΡΓΑΣΙΑΣ: ΣΥΝΟΛΙΚΗ ΠΑΡΟΥΣΙΑΣΗ», σε
«4.1β ΠΙΝΑΚΑΣ ΕΝΟΤΗΤΩΝ ΕΡΓΑΣΙΑΣ: ΣΥΝΟΛΙΚΗ ΠΑΡΟΥΣΙΑΣΗ»
(πρόκειται για δικό μας σφάλμα στην αρίθμηση που σας στείλαμε).

4.    Kαθώς το πεδίο 4.1 βρίσκεται στην «καρδιά» της προσέγισής μας για την Πρόσκληση, είναι πολύ σημαντικό και θα θέλαμε:

-      Να διατηρηθεί μεν, ως έχει το πεδίο «4.1α Κ.Α.Δ. ΕΠΕΝΔΥΤΙΚΟΥ ΣΧΕΔΙΟΥ (NACE Level Group)», το οποίο θα λαμβάνει τιμές από drop-down lists, καθώς επίσης

-      Να προστεθεί πεδίο free-text, στο οποίο οι δυνητικοί δικαιούχοι θα μπορούν να τεκμηριώσουν (λεκτικά) την συνεισφορά της πρότασής τους στη συγκεκριμένη αλυσίδα αξίας,
όπως περιλαμβάνονται στο έντυπο που σας αποστείλλαμε:

4.1

Κ.Α.Δ. ΕΠΕΝΔΥΤΙΚΟΥ ΣΧΕΔΙΟΥ (NACE Level Group)


Α/Α

Κωδικός

Περιγραφή Κ.Α.Δ.

Ημερομηνία ενεργοποίησης ΚΑΔ

1

ΕΠΙΛΟΓΗ ΑΠΟ ΛΙΣΤΑ ΟΠΟΥ ΠΕΡΙΕΧΕΙ ΤΟΥΣ ΕΠΙΛΕΞΙΜΟΥΣ Κ.Α.Δ. ΒΑΣΕΙ ΤΗΣ ΠΡΟΣΚΛΗΣΗΣ

ΕΠΙΛΟΓΗ ΑΠΟ ΛΙΣΤΑ ΟΠΟΥ ΠΕΡΙΕΧΕΙ ΤΟΥΣ ΕΠΙΛΕΞΙΜΟΥΣ Κ.Α.Δ. ΒΑΣΕΙ ΤΗΣ ΠΡΟΣΚΛΗΣΗΣ

ΒΑΣΕΙ ΔΙΚΑΙΟΛΟΓΗΤΙΚΟΥ

2

Τεκμηρίωση συνεισφοράς πρότασης στην αλυσίδα αξίας του κλάδου


Ελεύθερο πεδίο τεκμηρίωσης συνάφειας














5.    Επιπρόσθετα, στην ενότητα «4.4.α Έργα Έρευνας και Ανάπτυξης (ΕΚ 651/2014 (Άρθ. 25)» τόσο στην κατηγορία «II ΒΙΟΜΗΧΑΝΙΚΗ / ΕΦΑΡΜΟΣΜΕΝΗ ΕΡΕΥΝΑ (ΕΝΤΑΣΗ ΕΝΙΣΧΥΣΗΣ 50%», όσο και στην «III ΠΕΙΡΑΜΑΤΙΚΗ ΑΝΑΠΤΥΞΗ (ΕΝΤΑΣΗ ΕΝΙΣΧΥΣΗΣ 25%)», εφόσον είναι θετική η απάντηση στην 2η ερώτηση (της κάθε κατηγορίας) «Τα αποτελέσματα του έργου διαδίδονται ευρέως μέσω συνεδρίων, δημοσιεύσεων, αποθετηρίων ελεύθερης πρόσβασης ή μέσω δωρεάν λογισμικού ή λογισμικού ανοικτής πηγής;», θα πρέπει να εμφανίζεται επιπλέον «πεδίο» που θα προτρέπει σε τεκμηρίωση της απάντησης, όπως περιλαμβάνεται στο έντυπο που σας αποστείλλαμε:

ΕΑΝ ΝΑΙ ΤΕΚΜΗΡΙΩΣΗ (ΠΕΡΙΓΡΑΦΗ)
Εφόσον η επενδυτική πρόταση περιλαμβάνει «χρηματοδοτική ενίσχυση προσαυξημένη κατά 15%, διότι τα αποτελέσματα του έργου διαδίδονται ευρέως», τότε, τα αποτελέσματα της έρευνας (όχι μόνο τα συνολικά παραδοτέα του έργου) θα πρέπει να διαδοθούν στο ευρύτερο δυνατό βαθμό, τόσο σε εθνικό όσο και σε κοινοτικό επίπεδο (Ε.Ε.). Οι ανωτέρω προτάσεις θα πρέπει να περιλαμβάνουν στο χρονοπρογραμματισμό τους και ένα σχέδιο δράσεων για τη διάδοση των ερευνητικών αποτελεσμάτων του έργου.


6.    Στο 5ο Βήμα, στην ενότητα 5.1 (που μάλλον υλοποιείτε τώρα…), καλό θα ήταν να προστεθεί και η τελευταία στήλη του σχετικού Πίνακα που σας αποστείλλαμε, ενημερωτικά, προς διευκόλυνση δηλαδή των δικαιούχων κατά τη διαδικασία υποβολής των προτάσεων.



Κατηγορία δαπάνης

Π/Υ

Μέγιστο επιλέξιμο
ποσό ή %,
στον επιχορηγούμενο Π/Υ του έργου ή
μέγιστο ποσό (€)

ΕΚ 651/ 2014, Άρθρο 25, Ενισχύσεις για έργα έρευνας & ανάπτυξης



α1)

Δαπάνες προσωπικού με σύμβαση εξηρτημένης σχέσης εργασίας (υφιστάμενο ή/και νέο) στο βαθμό που απασχολούνται στο έργο.

€

25% - 70%[1]

α2)

Δαπάνες προσωπικού με σύμβαση μίσθωσης έργου στο βαθμό που απασχολούνται στο έργο.

€



β1)

Δαπάνες για όργανα, μηχανήματα, εξοπλισμό

€

40%

β2)

Δαπάνες για κτίρια, εγκαταστάσεις

€

35%

γ1)

Δαπάνες για «έρευνα επί συμβάσει»/ υπεργολαβία

€

40%

γ2)

Δαπάνες για «αγορά τεχνολογίας – τεχνογνωσίας» που αγοράστηκαν ή ελήφθησαν με άδεια εκμετάλλευσης από εξωτερικές πηγές, καθώς και δαπάνες απόκτησης επικύρωσης & προστασίας διπλωμάτων ευρεσιτεχνίας, στο εσωτερικό ή/και στο εξωτερικό

€

40%

δ1)

Πρόσθετα γενικά έξοδα και λοιπές λειτουργικές δαπάνες: Μετακινήσεις και λοιπές δαπάνες

€

10%

δ2)

Πρόσθετα γενικά έξοδα και λοιπές λειτουργικές δαπάνες: Αναλώσιμα και πρόσθετα έξοδα.

€

25%

ε)

Μελέτες τεχνικής σκοπιμότητας

€

< €14,000

ΕΚ 651/ 2014, Άρθρο 28, Ενισχύσεις καινοτομίας για ΜΜΕ



α)

Δαπάνες απόκτησης επικύρωσης και προστασίας διπλωμάτων ευρεσιτεχνίας, στο εσωτερικό ή/και στο εξωτερικό

€

100%

β)

Δαπάνες για την απόσπαση, από οργανισμό έρευνας και διάδοσης γνώσεων ή από μεγάλη επιχείρηση, προσωπικού υψηλής ειδίκευσης, το οποίο απασχολείται σε δραστηριότητες έρευνας, ανάπτυξης και καινοτομίας σε νέες θέσεις που έχουν δημιουργηθεί προς τον σκοπό αυτό στη δικαιούχο επιχείρηση και δεν αντικαθιστά άλλο προσωπικό.

€

100%

γ)

Δαπάνες για συμβουλευτικές και υποστηρικτικές υπηρεσίες στον τομέα της καινοτομίας.

€

< €14,000



ΣΥΝΟΛΟ

€



[1] Συνολικά, οι «Δαπάνες προσωπικού με σύμβαση εξηρτημένης σχέσης εργασίας» και οι «Δαπάνες προσωπικού με σύμβαση μίσθωσης έργου», θα πρέπει να αποτελούν τουλάχιστον το 25%, ενώ δεν θα πρέπει να υπερβαίνουν το 70% του επιχορηγούμενου Π/Υ του έργου.

Αυτά τα «ολίγα» (προς το παρόν…)!
Με εκτίμηση,

Ιωάννης Κεσανλής
Μονάδα A', Προγραμματισμού & Αξιολόγησης
Ειδική Υπηρεσία Διαχείρισης Επιχειρησιακού Προγράμματος
Περιφέρειας Ανατολικής Μακεδονίας και Θράκης
Δ/νση:  Ηροδότου 28, 69132 Κομοτηνή
Τηλ:     2531352332
Fax:     2531081601
E-mail: ikessanlis@mou.gr<mailto:ikessanlis@mou.gr>
Web:    www.eydamth.gr<http://www.eydamth.gr/>

**Comment by apanagio** [comment]
Δημιούργησα ξεχωριστά issues για το καθένα, οπότε κλείνει
