### ISSUE TITLE
Διόρθωση Μάσκας "9 Δείκτες"

### ISSUE THREAD

**Issue by ikessanlis** [mou-gr/forms#20]
Από δικό μας σφάλμα, στο έγγραφο που σας αποστείλαμε, προστέθηκε στον Πίνακα "9. ΔΕΙΚΤΕΣ ΑΞΙΟΛΟΓΗΣΗΣ – ΑΠΟΤΙΜΗΣΗΣ ΤΟΥ ΕΡΓΟΥ – ΣΥΜΒΟΛΗ ΣΤΗΝ ΕΠΙΤΕΥΞΗ ΤΩΝ ΓΕΝΙΚΟΤΕΡΩΝ ΣΤΟΧΩΝ ΤΩΝ ΔΡΑΣΕΩΝ", και ο Δείκτης Αποτελέσματος "Τ1012. Δαπάνες Ε&Α επιχειρήσεων ως ποσοστό του Περιφερειακού ΑΕΠ".  Παρακαλούμε όπως αφαιρεθεί όλο το τμήμα "9.1.1 Δείκτες αποτελέσματος".

Επίσης, ο τίτλος "9.1 ΔΕΙΚΤΕΣ σύμφωνα με τα απαιτούμενα από ΠΕΠ Δυτική Ελλάδα 2014-2020" θα πρέπει να διορθωθεί σε: "9.1 ΔΕΙΚΤΕΣ σύμφωνα με τα απαιτούμενα από το Επιχειρησιακό Πρόγραμμα
Περιφέρειας Ανατολικής Μακεδονίας και Θράκης"

**Comment by apanagio** [comment]
done

**Comment by ikessanlis** [comment]
Thank U!

...αλλά:
Εφόσον αφαιρέθηκε όλο το τμήμα "9.1.1 Δείκτες αποτελέσματος", θα πρέπει να αλλάξει η αρίθμηση στο εναπομείναν τμήμα, και από "9.1.2 Δείκτες εκροών", να γίνει "9.1.1 Δείκτες εκροών".

**Comment by apanagio** [comment]
done

**Comment by ikessanlis** [comment]
Ευχαριστούμε! -
