### ISSUE TITLE
Φόρμα Αξιολόγησης

### ISSUE THREAD

**Issue by ikessanlis** [mou-gr/forms#25]
1. Στα φύλλα "Β" έως "Δ", της φόρμας αξιολόγησης, η περιγραφή της προτελευταίας στήλης, σύμφωνα με το πρότυπο που σας έχει αποσταλεί, είναι "Συντελεστής Στάθμισης". Καθώς, πιθανώς, αυτό να δημιουργεί πρόβλημα ομοιομορφίας μεταξύ των στηλών, ίσως να πρέπει να αντικατασταθεί από τη λέξη "Βαρύτητα" (αντί του "Βάρος" που έχει επιλεγεί).

2. Στο κριτήριο Β.2, να ενωθεί η λέξη "εργαζομένων" ("Αξιολογείται η μεταβολή της απασχόληση στην επιχείρηση (ΕΜΕ) (αύξηση ή μείωση αριθμού εργαζο-μένων κατά την τελευταία τριετία ή διετία, για όσες έχουν μόνο 2 κλεισμένες χρήσεις)").

3. Σε όλα τα κριτήρια (εκτός του τελευταίου) του Σταδίου "Β. Κατάσταση Επιχείρησης" (Β.1 έως και Β.7), να μπουν από μία γραμμή σε κάθε εγγραφή (ανάλυση βαθμολογίας) στην στήλη "Ανάλυση".

4. Στο κριτήριο Γ1, να μπει από μία γραμμή σε κάθε εγγραφή (ανάλυση βαθμολογίας) στην στήλη "Ανάλυση".

5. Στο κριτήριο Γ1, να διορθωθεί ο Συντελεστής Στάθμισης ("Βάρος") σε 0,4 (αντί του 0,1).

6. Θα πρέπει να συζητήσουμε αναλυτικά για το τμήμα "5" (Ε?) "Αλλαγές στον Προϋπολογισμό", και
7. Αναμένουμε το τμήμα "6" (Αξιολόγηση των προτάσεων ανά ομάδα κριτηρίων).

**Comment by apanagio** [comment]
1. done
2. done
3. done
4. done
5. done

**Comment by ikessanlis** [comment]
Δεν τα βλέπω... Έχουν γίνει publish η αλλαγές?
Ευχαριστώ!

**Comment by apanagio** [comment]
Ναι είναι. 
Δες μήπως έιναι cached οι σελίδες στον browser 
Πάτα shift + ctrl + r για να ξανακατεβάσει όλη τη σελίδα

**Comment by ikessanlis** [comment]
OK!
