### ISSUE TITLE
AMΘ Φόρμα Υποβολής - Staging

### ISSUE THREAD

**Issue by ikessanlis** [mou-gr/forms#26]
1.	Να προσυμπληρωθεί (μόνιμα) το ακόλουθο κείμενο στο 1ο Tab (“1.1 ΘΕΜΑΤΙΚΟΣ ΤΟΜΕΑΣ ΠΡΟΤΕΡΑΙΟΤΗΤΑΣ (όπως σε: αναλυτική πρόσκληση δράσης) ”): «Επενδυτικά Σχέδια Καινοτομίας, Έρευνας και Ανάπτυξης Επιχειρήσεων»

2.	Το: “3Α.1.1.10 ΜΕΓΕΘΟΣ ΕΠΙΧΕΙΡΗΣΗΣ” σημαίνει control -  ενδεικτικά: θα πρέπει να επιβεβαιωθεί από την αξιολόγηση.

3.	Στο πεδίο «3Α.1.1.6 V.A.T. (ΕΚΤΟΣ ΕΛΛΑΔΟΣ)», μετά τη λέξη «Ελλάδος» θα πρέπει να προστεθεί παύλα και η λέξη « - ΧΩΡΑ».

4.	Tα πεδία «3Α.2. ΔΙΕΥΘΥΝΣΗ ΕΔΡΑΣ» και «3Β. ΒΑΣΙΚΑ ΣΤΟΙΧΕΙΑ ΤΟΠΟΥ ΥΛΟΠΟΙΗΣΗΣ ΤΟΥ ΕΡΓΟΥ» να “ανοίγουν” μόνο αν διαφέρουν από το «3Α.1.1 ΓΕΝΙΚΑ ΣΤΟΙΧΕΙΑ», με tick-box & drop-down σε περίπτωση επιλογής (όπως δηλαδή το «3Γ. ΣΤΟΙΧΕΙΑ ΝΟΜΙΜΟΥ ΕΚΠΡΟΣΩΠΟΥ» «3Γ.1 Άλλος από τον συντονιστή»).

5.	Τα πεδία του «3Ε.1 ΣΥΓΚΕΝΤΡΩΤΙΚΑ ΣΤΟΙΧΕΙΑ ΜΕΓΕΘΟΥΣ ΕΠΙΧΕΙΡΗΣΗΣ», για τα μεγέθη «ΣΥΝΟΛΙΚΟΣ ΚΥΚΛΟΣ ΕΡΓΑΣΙΩΝ (ΣΕ €)» και «ΣΥΝΟΛΟ ΕΤΗΣΙΟΥ ΙΣΟΛΟΓΙΣΜΟΥ (ΣΕ €)» να γίνουν σε €, όπως τα προηγούμενα του «3.Δ.2.2 Συνεργαζόμενες Επιχειρήσεις (βάσει της δήλωσης που υποβλήθηκε)».

6.	Το ίδιο και για τα πεδία του «3Ε.3 ΟΙΚΟΝΟΜΙΚΗ ΚΑΤΑΣΤΑΣΗ ΕΠΙΧΕΙΡΗΣΗΣ».

7.	Οι δε στήλες «ΣΥΝΟΛΙΚΟΣ ΚΥΚΛΟΣ ΕΡΓΑΣΙΩΝ (ΣΕ €)» και «ΑΡΙΘΜΟΣ ΑΠΑΣΧΟΛΟΥΜΕΝΩΝ (ΣΕ ΕΜΕ)», για τα έτη 2013-2015, του ίδιου Πίνακα (3Ε.3), να τροφοδοτούνται αυτόματα από τα αντίστοιχα του προηγούμενου Πίνακα (3Ε.1).

8.	Το πεδίο «4.1α Κ.Α.Δ. ΕΠΕΝΔΥΤΙΚΟΥ ΣΧΕΔΙΟΥ (NACE Level Group)» να δέχεται και «κενό» ή «Άλλο»

9.	Στο πεδίο «4.1β ΠΙΝΑΚΑΣ ΕΝΟΤΗΤΩΝ ΕΡΓΑΣΙΑΣ: ΣΥΝΟΛΙΚΗ ΠΑΡΟΥΣΙΑΣΗ» μήπως τα «Έναρξη (μήνας)» και «Τέλος (μήνας)» πρέπει να γίνουν drop-down menu? 
10.	Επίσης, στο ίδιο πεδίο, οι «Α/Μ» δεν έχουν περιορισμό? Δηλ. μπορώ να βάλω π.χ. 12,000 ανθρωπομήνες?!

11.	Στο πεδίο «4.2 ΠΙΝΑΚΑΣ ΠΑΡΑΔΟΤΕΩΝ: ΣΥΝΟΛΙΚΗ ΠΑΡΟΥΣΙΑΣΗ» μήπως το «Παράδοση (μήνας)» πρέπει να γίνει drop-down menu? 

12.	Στο πεδίο «4.4 ΤΕΚΜΗΡΙΩΣΗ ΠΡΟΣΑΥΞΗΣΗΣ ΠΟΣΟΣΤΟΥ ΕΝΙΣΧΥΣΗΣ», θα πρέπει να υπάρχει η δυνατότητα επιλογής μόνον ενός από τα tick, και όχι περισσότερων.

13.	Που θα γίνεται η επισύναψη του ηλεκ. αρχείου?

14.	Σε πολλά πεδία επιτρέπεται να καταχωρηθούν αλλοπρόσαλλα νούμερα. Χρειάζεται αρκετούς «λογικούς» ελέγχους σε πολλά από αυτά.

**Comment by apanagio** [comment]
done
Στους μήνες δεν έβαλα dropdown αλλά περιόρισα τις τιμές που μπορούν να πάρουν [0, 50]

**Comment by ikessanlis** [comment]
Να γίνει το ίδιο και στο "«8. ΧΡΟΝΟΔΙΑΓΡΑΜΜΑ ΑΝΑ ΦΟΡΕΑ»" (issue 24).

**Comment by apanagio** [comment]
done

**Comment by ikessanlis** [comment]
OK
