### ISSUE TITLE
AMΘ Φόρμα Υποβολής - Staging 2

### ISSUE THREAD

**Issue by ikessanlis** [mou-gr/forms#27]
15.	Ως συνέχεια από το issue 12 (ανωτέρω), θα πρέπει στις μάσκες του 5:
-	«5.1 ΣΥΓΚΕΝΤΡΩΤΙΚΗ ΠΑΡΟΥΣΙΑΣΗ ΤΟΥ ΠΡΟΫΠΟΛΟΓΙΣΜΟΥ ΤΟΥ ΕΡΓΟΥ ΑΝΑ ΚΑΤΗΓΟΡΙΑ ΔΑΠΑΝΗΣ», 
-	«5.2 ΠΡΟΫΠΟΛΟΓΙΣΜΟΣ ΑΝΑ ΕΝΟΤΗΤΑ ΕΡΓΑΣΙΑΣ ΚΑΙ ΚΑΤΗΓΟΡΙΑ ΕΡΕΥΝΑΣ», και
-	«5.3.1 ΑΝΑΛΥΣΗ ΤΟΥ ΠΡΟΫΠΟΛΟΓΙΣΜΟΥ ΑΝΑ ΚΑΤΗΓΟΡΙΑ ΔΑΠΑΝΗΣ», 
να ανοίγει μόνον το μενού που σχετίζεται με την επιλογή που έχει κάνει ο υποψήφιος στο «4.4 ΤΕΚΜΗΡΙΩΣΗ ΠΡΟΣΑΥΞΗΣΗΣ ΠΟΣΟΣΤΟΥ ΕΝΙΣΧΥΣΗΣ».

16.	Να αλλάξει η αρίθμηση από το «5.3.1 ΑΝΑΛΥΣΗ ΤΟΥ ΠΡΟΫΠΟΛΟΓΙΣΜΟΥ ΑΝΑ ΚΑΤΗΓΟΡΙΑ ΔΑΠΑΝΗΣ», να γίνει «5.3» και αντίστοιχα τα 5.3.1.1 σε 5.3.1, το 5.3.1.2 σε 5.3.2, κλπ.

17.	Το «5.4 ΚΑΤΑΝΟΜΗ ΤΟΥ ΣΥΝΟΛΙΚΟΥ ΠΡΟΫΠΟΛΟΓΙΣΜΟΥ ΚΑΙ ΤΗΣ ΔΗΜΟΣΙΑΣ ΔΑΠΑΝΗΣ ΑΝΑ ΣΥΜΜΕΤΕΧΟΝΤΑ ΦΟΡΕΑ ΚΑΙ ΠΕΡΙΦΕΡΕΙΑ» θα πρέπει να συμπληρώνεται αυτόματα…(?)

18.	Τα στοιχεία του Πίνακα «5.1 ΣΥΓΚΕΝΤΡΩΤΙΚΗ ΠΑΡΟΥΣΙΑΣΗ ΤΟΥ ΠΡΟΫΠΟΛΟΓΙΣΜΟΥ ΤΟΥ ΕΡΓΟΥ ΑΝΑ ΚΑΤΗΓΟΡΙΑ ΔΑΠΑΝΗΣ» θα πρέπει να «γεμίζουν» αυτόματα από τους ακόλουθους Πίνακες 5.1, 5.2 και 5.3.1 (5.3).

19.	Γενικά, πρέπει να δοθεί προσοχή στο «5. ΟΙΚΟΝΟΜΙΚΑ ΣΤΟΙΧΕΙΑ ΤΟΥ ΕΡΓΟΥ», καθώς είναι ιδιαίτερα σημαντικοί οι έλεγχοι που πρέπει να γίνονται στα ποσά που θα βάζει ο υποψήφιος, σε αντιπαραβολή με τα ποσοστά που δικαιούται   – με βάση τους πίνακες της Πρόσκλησης. Να βγάζει «alerts» σε περιπτώσεις «υπερβάσεων» (?)

20.	Στη στήλη «Δημόσια Δαπάνη (€)» του Πίνακα «5.2 ΠΡΟΫΠΟΛΟΓΙΣΜΟΣ ΑΝΑ ΕΝΟΤΗΤΑ ΕΡΓΑΣΙΑΣ ΚΑΙ ΚΑΤΗΓΟΡΙΑ ΕΡΕΥΝΑΣ», το ανώτατο όριο, ορίζεται από την Πρόσκληση ανά κατηγορία δραστηριότητας, είδος φορέα και μέγεθος επιχείρησης.

21.	Στο «7. ΑΙΤΟΥΜΕΝΕΣ ΑΔΕΙΕΣ Ή ΕΓΚΡΙΣΕΙΣ», θα  πρέπει να αφαιρεθεί εντελώς το πεδίο «7.2 Απαιτούνται για την υλοποίηση του ερευνητικού έργου ειδικές άδειες ή εγκρίσεις;»  (και το tick που το συνοδεύει), καθώς αποτελεί πλεονασμό. Θα πρέπει όμως, στο «7.1 Υπάρχουν για την υλοποίηση του ερευνητικού έργου όλες οι απαιτούμενες άδειες;», να γραφεί ολογράφως η επιλογή «Δεν Απαιτούνται», αντί του «ΔΑ».

22.	Στο «8. ΧΡΟΝΟΔΙΑΓΡΑΜΜΑ ΑΝΑ ΦΟΡΕΑ», να περιοριστεί ο αριθμός που μπορεί να εισάγει ο υποψήφιος από «0» έως «60».

**Comment by apanagio** [comment]
5.2 Μόνο ένας δικαιούχος

**Comment by apanagio** [comment]
done
 εκτος από τα αυτόματα αθροίσματα για τα οποία ανοίγω ξεχωριστά issues

**Comment by ikessanlis** [comment]
OK
