### ISSUE TITLE
AMΘ Φόρμα Υποβολής - Staging 3

### ISSUE THREAD

**Issue by ikessanlis** [mou-gr/forms#28]
23.	Να διαγραφεί το πεδίο «3Α.1.1.10 ΜΕΓΕΘΟΣ ΕΠΙΧΕΙΡΗΣΗΣ». Δεν έχει νόημα ύπαρξης, καθώς το ερώτημα, επαναλαμβάνεται ουσιαστικά, στο πεδίο «3Ε.2 ΧΑΡΑΚΤΗΡΙΣΜΟΣ ΕΠΙΧΕΙΡΗΣΗΣ ΜΕ ΒΑΣΗ ΤΟ ΜΕΓΕΘΟΣ ΤΗΣ ΣΥΜΦΩΝΑ ΜΕ ΤΟΝ ΚΑΝ. (ΕΚ) 651/2014 (ΠΑΡΑΡΤΗΜΑ ΙV ΤΟΥ ΟΔΗΓΟΥ)». Στο δε πεδίο «3Ε.2», θα πρέπει να μπει το «drop-down menu» με τις επιλογές του «3Α.1.1.10». 

24.	Κατόπιν των αλλαγών που ήδη πραγματοποιήθηκαν, στο «8. ΧΡΟΝΟΔΙΑΓΡΑΜΜΑ ΑΝΑ ΦΟΡΕΑ», να περιοριστεί ο αριθμός που μπορεί να εισάγει ο υποψήφιος από «0» έως «50».

**Comment by apanagio** [comment]
done

**Comment by ikessanlis** [comment]
ok
