### ISSUE TITLE
Προσθήκη σε τμήμα 3

### ISSUE THREAD

**Issue by apanagio** [mou-gr/forms#3]
3.ΣΤ

Περιγράφονται με τρόπο απόλυτα κατανοητό τα παρακάτω πεδία που αφορούν στην επιχείρηση:

  1.  Σύντομο ιστορικό, έτος έναρξης δραστηριότητας της επιχείρησης,
  2.  Περιγραφή Στρατηγικής της επιχείρησης,
  3.  Ανάλυση επιχειρηματικής δραστηριότητας,
  4.  Διαδικασίες οργάνωσης - προσωπικό,
  5.  Συνοπτική παρουσίαση της παραγωγικής διαδικασίας.

Επιπλέον, εφόσον υπάρχουν, μνημονεύονται:

  1.  Παραγωγικά μέσα για έρευνα (προσωπικό, εξοπλισμός, κονδύλια) - Επίπεδα Τεχνολογικής Ετοιμότητας,
  2.  Συμμετοχές σε Ευρωπαϊκούς ή Διεθνείς διαγωνισμούς που διοργανώθηκαν από κοινοτικό, εθνικό, διεθνή ή εμπορικό φορέα και έχει βραβευτεί ή διακριθεί σε κάποια κατηγορία,
  3.  Εμπορικά Σήματα,
  4.  Συστήματα διασφάλισης ποιότητας παραγωγικής διαδικασίας,
  5.  Συστήματα αυτομ/σης για την παρακολούθηση και τον έλεγχο της "παραγωγικής" διαδικασίας,
  6.  Εξειδικευμένα Λογισμικά (ERP, CRM, Logistics, κ.α.),
  7.  Ηλεκτρονικές πωλήσεις,
  8.  Αυτόματα συστήματα παραγγελιοληψίας (remote, κ.α.),
  9.  Οργανωμένη προβολή (επαγγελματικοί οδηγοί, μηχανές αναζήτησης),
  10. Λειτουργία e-shop,
  11. Εταιρική ιστοσελίδα,
  12. Συμφωνητικά ή και Προσύμφωνα πώλησης νέων προϊόντων/ υπηρεσιών,

Μήπως σκοπεύετε να το εντάξετε σε κάποια άλλη ενότητα του εντύπου;

**Comment by apanagio** [comment]
Θα τα εντάξω στο τέλοςτης ενότητας

**Comment by apanagio** [comment]
done

**Comment by ikessanlis** [comment]
Το αίτημα υλοποιήθηκε.
Μήπως όμως θα έπρεπε να βάλουμε (με μικρότερη γραμματοσειρά & δίχως «έντονη γραφή»-bold- ίσως…?) και σύντομες «οδηγίες» σχετικά με το "όριο" των λέξεων-χαρακτήρων σε κάθε πεδίο, όπως π.χ. στο πεδίο "4α. Περιγραφή Επενδυτικού Σχεδίου (έως 1000 χαρακτήρες)"?
Ευχαριστώ!

**Comment by apanagio** [comment]
done.

**Comment by ikessanlis** [comment]
Completed.-
