### ISSUE TITLE
Προσθήκη περιγραφών στην ενότητα 4

### ISSUE THREAD

**Issue by apanagio** [mou-gr/forms#4]
2.    Προχωρώντας στο 4ο Βήμα, στις ενότητες 4α έως και 4γ, καλό θα ήταν, εφόσον είναι εφικτό, να προσθέταμε (με μικρότερη γραμματοσειρά & δίχως «έντονη γραφή»-bold- ίσως…?) και τις σύντομες «οδηγίες» που περιλαμβάνονται στο έντυπο που σας αποστείλλαμε (με πλάγια γράμματα στο υπόδειγμα – “italics”)

**Comment by apanagio** [comment]
Θα προστεθούν στο βήμα 4 και οι περιγραφές

**Comment by apanagio** [comment]
Έγινε
Γιάννη σε παρακαλώ επιβεβαίωσε και κλείσε την ενότητα

**Comment by ikessanlis** [comment]
Ολοκληρώθηκε.-
