### ISSUE TITLE
Μετονομασίες στο τμήμα 4

### ISSUE THREAD

**Issue by apanagio** [mou-gr/forms#5]
3.    Περαιτέρω, προς αποφυγή παρανοήσεων, και διευκόλυνση της διαδικασίας αξιολόγησης, μάλλον θα πρέπει να μετονομάσουμε την ενότητα
«4.1 Κ.Α.Δ. ΕΠΕΝΔΥΤΙΚΟΥ ΣΧΕΔΙΟΥ (NACE Level Group)», σε
«4.1α Κ.Α.Δ. ΕΠΕΝΔΥΤΙΚΟΥ ΣΧΕΔΙΟΥ (NACE Level Group)»,
και την ενότητα
«4.1 ΠΙΝΑΚΑΣ ΕΝΟΤΗΤΩΝ ΕΡΓΑΣΙΑΣ: ΣΥΝΟΛΙΚΗ ΠΑΡΟΥΣΙΑΣΗ», σε
«4.1β ΠΙΝΑΚΑΣ ΕΝΟΤΗΤΩΝ ΕΡΓΑΣΙΑΣ: ΣΥΝΟΛΙΚΗ ΠΑΡΟΥΣΙΑΣΗ»
(πρόκειται για δικό μας σφάλμα στην αρίθμηση που σας στείλαμε).

**Comment by apanagio** [comment]
done

**Comment by ikessanlis** [comment]
Indeed!
