### ISSUE TITLE
Προσθήκη πεδίου στο 4.1

### ISSUE THREAD

**Issue by apanagio** [mou-gr/forms#6]
4.    Kαθώς το πεδίο 4.1 βρίσκεται στην «καρδιά» της προσέγισής μας για την Πρόσκληση, είναι πολύ σημαντικό και θα θέλαμε:

-      Να διατηρηθεί μεν, ως έχει το πεδίο «4.1α Κ.Α.Δ. ΕΠΕΝΔΥΤΙΚΟΥ ΣΧΕΔΙΟΥ (NACE Level Group)», το οποίο θα λαμβάνει τιμές από drop-down lists, καθώς επίσης

-      Να προστεθεί πεδίο free-text, στο οποίο οι δυνητικοί δικαιούχοι θα μπορούν να τεκμηριώσουν (λεκτικά) την συνεισφορά της πρότασής τους στη συγκεκριμένη αλυσίδα αξίας,
όπως περιλαμβάνονται στο έντυπο που σας αποστείλλαμε:

4.1

Κ.Α.Δ. ΕΠΕΝΔΥΤΙΚΟΥ ΣΧΕΔΙΟΥ (NACE Level Group)

Α/Α

Κωδικός

Περιγραφή Κ.Α.Δ.

Ημερομηνία ενεργοποίησης ΚΑΔ

1

ΕΠΙΛΟΓΗ ΑΠΟ ΛΙΣΤΑ ΟΠΟΥ ΠΕΡΙΕΧΕΙ ΤΟΥΣ ΕΠΙΛΕΞΙΜΟΥΣ Κ.Α.Δ. ΒΑΣΕΙ ΤΗΣ ΠΡΟΣΚΛΗΣΗΣ

ΕΠΙΛΟΓΗ ΑΠΟ ΛΙΣΤΑ ΟΠΟΥ ΠΕΡΙΕΧΕΙ ΤΟΥΣ ΕΠΙΛΕΞΙΜΟΥΣ Κ.Α.Δ. ΒΑΣΕΙ ΤΗΣ ΠΡΟΣΚΛΗΣΗΣ

ΒΑΣΕΙ ΔΙΚΑΙΟΛΟΓΗΤΙΚΟΥ

2

Τεκμηρίωση συνεισφοράς πρότασης στην αλυσίδα αξίας του κλάδου

Ελεύθερο πεδίο τεκμηρίωσης συνάφειας

**Comment by apanagio** [comment]
done
Δείτε μήπως θέλετε κάτι άλλο αντί για "Επιπλεόν ΚΑΔ"

**Comment by ikessanlis** [comment]
Με τον τρόπο που υλοποιήθηκε, δεν είμαι σίγουρος ότι ο δυνητικός δικαιούχος δεν θα αποκλείεται από τη διαδικασία, λόγω μη ύπαρξης ΚΑΔ που να περιλαμβάνεται στην Πρόσκληση. Ας το επιλύσουμε τηλεφωνικά.

Επίσης, μήπως θα έπρεπε να βάλουμε (με μικρότερη γραμματοσειρά & δίχως «έντονη γραφή»-bold- ίσως…?) και σύντομες «οδηγίες» σχετικά με το "όριο" των λέξεων-χαρακτήρων στο πεδίο "Τεκμηρίωση συνεισφοράς πρότασης στην αλυσίδα αξίας του κλάδου", όπως π.χ. στο πεδίο "4α. Περιγραφή Επενδυτικού Σχεδίου (έως 1000 χαρακτήρες)"?

**Comment by apanagio** [comment]
done

**Comment by ikessanlis** [comment]
Completed.-
