### ISSUE TITLE
Προσθήκη πεδίου στο 4.4

### ISSUE THREAD

**Issue by apanagio** [mou-gr/forms#7]
5.    Επιπρόσθετα, στην ενότητα «4.4.α Έργα Έρευνας και Ανάπτυξης (ΕΚ 651/2014 (Άρθ. 25)» τόσο στην κατηγορία «II ΒΙΟΜΗΧΑΝΙΚΗ / ΕΦΑΡΜΟΣΜΕΝΗ ΕΡΕΥΝΑ (ΕΝΤΑΣΗ ΕΝΙΣΧΥΣΗΣ 50%», όσο και στην «III ΠΕΙΡΑΜΑΤΙΚΗ ΑΝΑΠΤΥΞΗ (ΕΝΤΑΣΗ ΕΝΙΣΧΥΣΗΣ 25%)», εφόσον είναι θετική η απάντηση στην 2η ερώτηση (της κάθε κατηγορίας) «Τα αποτελέσματα του έργου διαδίδονται ευρέως μέσω συνεδρίων, δημοσιεύσεων, αποθετηρίων ελεύθερης πρόσβασης ή μέσω δωρεάν λογισμικού ή λογισμικού ανοικτής πηγής;», θα πρέπει να εμφανίζεται επιπλέον «πεδίο» που θα προτρέπει σε τεκμηρίωση της απάντησης, όπως περιλαμβάνεται στο έντυπο που σας αποστείλλαμε:

ΕΑΝ ΝΑΙ ΤΕΚΜΗΡΙΩΣΗ (ΠΕΡΙΓΡΑΦΗ)
Εφόσον η επενδυτική πρόταση περιλαμβάνει «χρηματοδοτική ενίσχυση προσαυξημένη κατά 15%, διότι τα αποτελέσματα του έργου διαδίδονται ευρέως», τότε, τα αποτελέσματα της έρευνας (όχι μόνο τα συνολικά παραδοτέα του έργου) θα πρέπει να διαδοθούν στο ευρύτερο δυνατό βαθμό, τόσο σε εθνικό όσο και σε κοινοτικό επίπεδο (Ε.Ε.). Οι ανωτέρω προτάσεις θα πρέπει να περιλαμβάνουν στο χρονοπρογραμματισμό τους και ένα σχέδιο δράσεων για τη διάδοση των ερευνητικών αποτελεσμάτων του έργου.

**Comment by ikessanlis** [comment]
Ολοκληρώθηκε.

Μήπως όμως, θα έπρεπε να βάλουμε (με μικρότερη γραμματοσειρά & δίχως «έντονη γραφή»-bold- ίσως…?) και σύντομες «οδηγίες» σχετικά με το "όριο" των λέξεων-χαρακτήρων στο πεδίο "ΕΑΝ ΝΑΙ ΤΕΚΜΗΡΙΩΣΗ (ΠΕΡΙΓΡΑΦΗ)", όπως π.χ. στο πεδίο "4α. Περιγραφή Επενδυτικού Σχεδίου (έως 1000 χαρακτήρες)"?

**Comment by ikessanlis** [comment]
Done.-
