### ISSUE TITLE
Αλλαγές στο τμήμα 5

### ISSUE THREAD

**Issue by apanagio** [mou-gr/forms#8]
Στο 5ο Βήμα, στην ενότητα 5.1 (που μάλλον υλοποιείτε τώρα…), καλό θα ήταν να προστεθεί και η τελευταία στήλη του σχετικού Πίνακα που σας αποστείλλαμε, ενημερωτικά, προς διευκόλυνση δηλαδή των δικαιούχων κατά τη διαδικασία υποβολής των προτάσεων.

Κατηγορία δαπάνης

Π/Υ

Μέγιστο επιλέξιμο
ποσό ή %,
στον επιχορηγούμενο Π/Υ του έργου ή
μέγιστο ποσό (€)

ΕΚ 651/ 2014, Άρθρο 25, Ενισχύσεις για έργα έρευνας & ανάπτυξης

α1)

Δαπάνες προσωπικού με σύμβαση εξηρτημένης σχέσης εργασίας (υφιστάμενο ή/και νέο) στο βαθμό που απασχολούνται στο έργο.

€

25% - 70%[1]

α2)

Δαπάνες προσωπικού με σύμβαση μίσθωσης έργου στο βαθμό που απασχολούνται στο έργο.

€

β1)

Δαπάνες για όργανα, μηχανήματα, εξοπλισμό

€

40%

β2)

Δαπάνες για κτίρια, εγκαταστάσεις

€

35%

γ1)

Δαπάνες για «έρευνα επί συμβάσει»/ υπεργολαβία

€

40%

γ2)

Δαπάνες για «αγορά τεχνολογίας – τεχνογνωσίας» που αγοράστηκαν ή ελήφθησαν με άδεια εκμετάλλευσης από εξωτερικές πηγές, καθώς και δαπάνες απόκτησης επικύρωσης & προστασίας διπλωμάτων ευρεσιτεχνίας, στο εσωτερικό ή/και στο εξωτερικό

€

40%

δ1)

Πρόσθετα γενικά έξοδα και λοιπές λειτουργικές δαπάνες: Μετακινήσεις και λοιπές δαπάνες

€

10%

δ2)

Πρόσθετα γενικά έξοδα και λοιπές λειτουργικές δαπάνες: Αναλώσιμα και πρόσθετα έξοδα.

€

25%

ε)

Μελέτες τεχνικής σκοπιμότητας

€

< €14,000

ΕΚ 651/ 2014, Άρθρο 28, Ενισχύσεις καινοτομίας για ΜΜΕ

α)

Δαπάνες απόκτησης επικύρωσης και προστασίας διπλωμάτων ευρεσιτεχνίας, στο εσωτερικό ή/και στο εξωτερικό

€

100%

β)

Δαπάνες για την απόσπαση, από οργανισμό έρευνας και διάδοσης γνώσεων ή από μεγάλη επιχείρηση, προσωπικού υψηλής ειδίκευσης, το οποίο απασχολείται σε δραστηριότητες έρευνας, ανάπτυξης και καινοτομίας σε νέες θέσεις που έχουν δημιουργηθεί προς τον σκοπό αυτό στη δικαιούχο επιχείρηση και δεν αντικαθιστά άλλο προσωπικό.

€

100%

γ)

Δαπάνες για συμβουλευτικές και υποστηρικτικές υπηρεσίες στον τομέα της καινοτομίας.

€

< €14,000

ΣΥΝΟΛΟ

€

[1] Συνολικά, οι «Δαπάνες προσωπικού με σύμβαση εξηρτημένης σχέσης εργασίας» και οι «Δαπάνες προσωπικού με σύμβαση μίσθωσης έργου», θα πρέπει να αποτελούν τουλάχιστον το 25%, ενώ δεν θα πρέπει να υπερβαίνουν το 70% του επιχορηγούμενου Π/Υ του έργου.

Αυτά τα «ολίγα» (προς το παρόν…)!
Με εκτίμηση,

**Comment by apanagio** [comment]
Είναι έτοιμο και περιμένουμε σχόλια.

Φαντάζομαι στο 5.4 που αναφέρεται η Δ. Ελλάδα είναι μάλλον από λάθος

**Comment by ikessanlis** [comment]
Στον Πίνακας 5.1, εφόσον είναι εφικτό, να προστεθεί η Υποσημείωση  1. "Συνολικά, οι «Δαπάνες προσωπικού με σύμβαση εξηρτημένης σχέσης εργασίας» και οι «Δαπάνες προσωπικού με σύμβαση μίσθωσης έργου», θα πρέπει να αποτελούν τουλάχιστον το 25%, ενώ δεν θα πρέπει να υπερβαίνουν το 70% του επιχορηγούμενου Π/Υ του έργου.", η οποία αφορά τα "α1" και "α2" του 5,1, μαζί.


Επίσης, στον ίδιο Πίνακα 5.1, οι γραμμές "ΕΚ 651/ 2014, Άρθρο 25, Ενισχύσεις για έργα έρευνας & ανάπτυξης" και "ΕΚ 651/ 2014, Άρθρο 28, Ενισχύσεις καινοτομίας για ΜΜΕ", να υπογραμμιστούν (bold?) ως υποκεφαλίδες - δεν χρειάζονται τα διπλανά άδεια κουτιά.


Στους Πίνακες που απαρτίζουν την ενότητα «5.1.2 ΑΝΑΛΥΤΙΚΗ ΠΑΡΟΥΣΙΑΣΗ ΤΟΥ ΠΡΟΫΠΟΛΟΓΙΣΜΟΥ ΤΟΥ ΕΡΓΟΥ ΑΝΑ ΚΑΤΗΓΟΡΙΑ ΔΑΠΑΝΗΣ», αποτελούν υποκεφαλίδες και δεν χρειάζονται τα διπλανά άδεια κουτιά, στα πεδία:
1	Δαπάνες προσωπικού		
2.	Δαπάνες Οργάνων & ερευνητικού εξοπλισμού		
3	Δαπάνες για έρευνα επί συμβάσει, γνώσεις και διπλώματα ευρεσιτεχνίας	
4. 	Πρόσθετα γενικά έξοδα και λοιπές λειτουργικές δαπάνες		
5	Δαπάνες για μελέτες σκοπιμότητας		
6	Δαπάνες προσωπικού		
7	Δαπάνες απόκτησης επικύρωσης και προστασίας διπλωμάτων ευρεσιτεχνίας	
8. 	Δαπάνες για συμβουλευτικές και υποστηρικτικές υπηρεσίες στον τομέα της 
9	Δαπάνες προσωπικού		
10.	Δαπάνες Οργάνων & ερευνητικού εξοπλισμού		
11	Δαπάνες για έρευνα επί συμβάσει, γνώσεις και διπλώματα ευρεσιτεχνίας	
12. 	Πρόσθετα γενικά έξοδα και λοιπές λειτουργικές δαπάνες		
13	Δαπάνες για μελέτες σκοπιμότητας


Στον Πίνακα 5.2 "ΠΡΟΫΠΟΛΟΓΙΣΜΟΣ ΑΝΑ ΕΝΟΤΗΤΑ ΕΡΓΑΣΙΑΣ ΚΑΙ ΚΑΤΗΓΟΡΙΑ ΕΡΕΥΝΑΣ", παρακαλούμε να προστεθούν οι επεξηγηματικές υποσημειώσεις: "2. ΒΙΕ: Βιομηχανική Έρευνα, ΠΕΑ: Πειραματική Ανάπτυξη, ΜΤΣ: Μελέτες Τεχνικής Σκοπιμότητας", και "3. Το ποσοστό του προϋπολογισμού του φορέα νοείται επί του συνολικού προϋπολογισμού του έργου".


Στον ίδιο Πίνακα, 5.2, στην 6η στήλη, μάλλον θα πρέπει να αφαιρεθεί ο τονισμός από τη λέξη "ΠΡΟΣΑΎΞΗΣΗ", καθώς είναι κεφαλαία γράμματα και δεν απαιτείται.

**Comment by apanagio** [comment]
done

**Comment by ikessanlis** [comment]
Σχετικά με την προτελευταία παρατήρηση μας, παρότι υλοποιήθηκε, παρακαλούμε να προστεθεί ο αντίστοιχος υπερθέτης (1 και 2) στα σημεία που γίνονται οι παραπομπές (ΕΙΔΟΣ ΕΡΕΥΝΑΣ=1, % επί του
συνολικού Π/Υ έργου=2). Για το λόγο αυτό (μάλλον) οι παραπομπές θα πρέπει να "κατέβουν" λίγο - μετά την ενότητα "Σύνολο Δικαιούχος" (ή τουλάχιστον η 2η παραπομπή).

**Comment by apanagio** [comment]
done.

**Comment by ikessanlis** [comment]
Στο τμήμα 5.1, νομίζω είναι λάθος ο τίτλος της στήλης "Μέγιστο επιλέξιμο ποσό ή %, στον επιχορηγούμενο Π/Υ του έργου ή μέγιστο ποσό (€)": το τελευταίο μέρος του τίτλου, "ή μέγιστο ποσό (€)" νομίζω ότι πρέπει να αφαιρεθεί, αφού είναι ουσιαστικά επανάληψη του προηγούμενου.

**Comment by ikessanlis** [comment]
Επίσης, από δικό μας σφάλμα, μπήκαν στη φόρμα και οι υποσημειώσεις που δεν απαιτούνται, στην 1η φάση της αξιολόγησης, και άρα θα πρέπει να αφαιρεθούν:

**Comment by ncppd** [comment]
ok

**Comment by ikessanlis** [comment]
Από δικό μας σφάλμα, στο έγγραφο που σας αποστείλαμε περιελήφθησαν και υποσημειώσεις, που θα πρέπει να αφαιρεθούν, καθώς δεν συνάδουν με τη διαδικασία αξιολόγησης που αποφασίσαμε να υιοθετήσουμε. Συγκεκριμένα στο υποκεφάλαιο "5.2 ΠΡΟΫΠΟΛΟΓΙΣΜΟΣ ΑΝΑ ΕΝΟΤΗΤΑ ΕΡΓΑΣΙΑΣ ΚΑΙ ΚΑΤΗΓΟΡΙΑ ΕΡΕΥΝΑΣ":

- Στο τμήμα «5.3.1.3 Δαπάνες για έρευνα επί συμβάσει και δαπάνες ΦΤΕ (Αμοιβές τρίτων – Υπεργολαβίες) (άρθρο 25, EK 651/2014)», παρακαλούμε να αφαιρεθεί η η υποσημείωση: “Απαιτείται προσύμφωνο συνεργασίας με τον αναφερόμενο φορέα, το οποίο θα πρέπει να επισυναφθεί σκαναρισμένο ηλεκτρονικά”.

- Στο τμήμα «5.3.1.4 Δαπάνες Μελέτες Τεχνικής Σκοπιμότητας (άρθρο 25, EK 651/2014)», παρακαλούμε να αφαιρεθεί η η υποσημείωση: “Απαιτείται προσύμφωνο συνεργασίας με τον αναφερόμενο φορέα, το οποίο θα πρέπει να επισυναφθεί σκαναρισμένο ηλεκτρονικά”.

- Στο τμήμα «5.3.1.5 Δαπάνες για αγορά τεχνογνωσίας (άρθρο 25, EK 651/2014)», παρακαλούμε να αφαιρεθεί η η υποσημείωση: “Απαιτείται προσφορά από τον αναφερόμενο φορέα”.

**Comment by ncppd** [comment]
ok

**Comment by ikessanlis** [comment]
Ζητώ συγνώμη για την αναστάτωση, αλλά θα ήθελα να ζητήσω να προσθέσουμε, ως υποσημείωση στην Ενότητα 5.3.1 "ΑΝΑΛΥΣΗ ΤΟΥ ΠΡΟΫΠΟΛΟΓΙΣΜΟΥ ΑΝΑ ΚΑΤΗΓΟΡΙΑ ΔΑΠΑΝΗΣ", το ακόλουθο κείμενο:

"Απαιτείται τεκμηρίωση κόστους, της κατηγορίας δαπανών «όργανα, εξοπλισμός και κτίρια», μέσω, είτε προσφορών/προτιμολογίων με αναλυτική περιγραφή δαπανών ανά είδος και αναγωγή κόστους ανά μετρική μονάδα, ή αντίστοιχα, επικοινωνίας με δυνητικούς προμηθευτές μέσω emails, ή έρευνας από το διαδίκτυο, καθώς και προωθητικών φυλλαδίων."

Σας ευχαριστούμε για όλα!

Γ.Κ.

**Comment by apanagio** [comment]
done

**Comment by ikessanlis** [comment]
Δεν το βλέπω... Έχει γίνει publish η αλλαγή?
Ευχαριστώ!

**Comment by apanagio** [comment]
τώρα είναι

**Comment by ikessanlis** [comment]
OK!
