### ISSUE TITLE
Στο τμήμα 8 δεν χρειάζονται οι μήνες

### ISSUE THREAD

**Issue by apanagio** [mou-gr/forms#9]
Στο τμήμα 8 δεν χρειάζονται οι μήνες, αρκούν οι υπόλοιπες στήλες.

**Comment by grtheod** [comment]
Οι στήλες με τα νούμερα;

**Comment by apanagio** [comment]
ναι ακριβώς

Ενδεχομένως να βάλουμε ενα μικρό gui που να απεικονίζει με ένα gant διάγραμμα την κατάσταση. Σε κάθε περίπτωση τα δεδομένα που χρειαζόμαστε είναι μόνο οι υπόλοιπες στήλες

**Comment by apanagio** [comment]
Βάλε αν μπορείς ένα default αντικείμενο για να φαίνεται η πρώτη γραμμή

**Comment by grtheod** [comment]
Το φτιάξαμε.
